name: 'Uppercase'
description: 'Convert text to uppercase'
author: 'nhayashi'

# Define your inputs here.
inputs:
  text:
    description: 'Text to be converted to uppercase'
    required: true

# Define your outputs here.
outputs:
  uppercase-text:
    description: 'Text converted to uppercase'

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.text }}

branding:
  icon: 'chevrons-up'
  color: 'green'
